server:
  port: 8081

logging:
  file:
    name: logs/蛮怪的日志.log
  level:
    root: warn


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/luoxiaohei?allowMultiQueries=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 6000
      maximum-pool-size: 16
      max-lifetime: 30000
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .html


mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml
